#!/bin/sh
set -eu

VERSION=${VERSION:-0.$(date +%Y%m%d%H%M)}
ci=
grunt_opts=

if ! test -t 1; then
  grunt_opts="--no-color"
fi

while test $# -gt 0; do
  case "$1" in
    -v)
      VERSION=$2;;
    --ci)
      ci=true;;
  esac
  shift
done

grunt --no-color test
if [ "$ci" = "true" ]; then
  sonar-scanner
fi

rm -f debian/changelog
dch --create --controlmaint --package decommissioned-sites -v $VERSION ""
./debian/rules clean
./debian/rules build
fakeroot ./debian/rules binary OUTDIR=.
