#!/bin/sh
# postinst script for decommissioned-sites
#
# see: dh_installdeb(1)

set -eu

configure() {
  # Set-up site user
  adduser \
    --quiet \
    --system \
    --home /opt/redirects \
    --no-create-home \
    --shell /bin/bash \
    --group \
    --gecos "Redirects" \
    redirects

  mkdir -p /srv/redirects
  chown -R redirects:redirects /srv/redirects
  /opt/redirects/push
 }

case "$1" in
    configure)
      configure
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
